# taken from https://github.com/j3ssie/sample-semgrep-ci/blob/main/.github/workflows/semgrep.yaml

name: Semgrep

on:
  push:

jobs:
  semgrep_scan:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4